name: Deploy to VPS

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy Application
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create .env file
        run: |
          echo "OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }}" > .env
          echo "REDIS_URL=${{ secrets.REDIS_URL }}" >> .env
        shell: bash


      - name: Sync project files to VPS
        run: |
          sudo cp .env /appify/.env
          sudo cp -r . /appify/
        shell: bash

      - name: Deploy on VPS with Docker Compose
        run: |
          sudo cd /appify
          sudo docker-compose down
          sudo docker-compose -f docker-compose.yml up -d --build
          echo "Pruning old Docker images..."
          sudo docker image prune -af
          echo "Deployment successful!"
        shell: bash
