name: Deploy to VPS 

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy with Rsync
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Create environment files
      run: |
        echo "Creating .env file..."
        cat > .env << EOF
        OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }}
        REDIS_URL=${{ secrets.REDIS_URL }}
        EOF

    - name: Install sshpass for password authentication
      run: sudo apt-get update && sudo apt-get install -y sshpass

    - name: Deploy via Rsync with Password
      run: |
        # Use sshpass for password authentication with rsync
        export SSHPASS="${{ secrets.VPS_PASSWORD }}"
        rsync -avzr --delete \
          --exclude=node_modules \
          --exclude=.git \
          --exclude=.github \
          --exclude=frontend \
          --timeout=600 \
          -e "sshpass -e ssh -o ConnectTimeout=60 -o ServerAliveInterval=30 -o ServerAliveCountMax=10 -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -p 2287" \
          ./ ${{ secrets.VPS_USERNAME }}@${{ secrets.VPS_HOST }}:~/appify/

    - name: Build and Deploy Docker Compose
      run: |
        export SSHPASS="${{ secrets.VPS_PASSWORD }}"
        sshpass -e ssh -o ConnectTimeout=60 -o ServerAliveInterval=30 -o ServerAliveCountMax=10 -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -p 2287 ${{ secrets.VPS_USERNAME }}@${{ secrets.VPS_HOST }} '
        cd ~/appify
        echo "Current directory: $(pwd)"
        echo "Listing files:"
        ls -la
        
        echo "Force stopping and removing existing container..."
        sudo docker-compose down
        
        sudo docker system prune -af --volumes
        sudo docker builder prune -af
        sudo docker-compose build
        sudo docker-compose up -d --build

        sudo docker-compose ps
        
        echo "Checking container status..."
        sudo docker ps | grep appify-app || echo "Container not running"
        
        echo "Checking container logs (last 10 lines)..."
        sudo docker logs --tail 10 appify-app || echo "No logs available"
        
        echo "Deployment completed successfully!"
        ' 